// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: pb/protoc/all.proto

package allpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code *int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  *string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (x *ErrInfo) Reset() {
	*x = ErrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfo) ProtoMessage() {}

func (x *ErrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfo.ProtoReflect.Descriptor instead.
func (*ErrInfo) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{0}
}

func (x *ErrInfo) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *ErrInfo) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type RegisterRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email      *string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Name       *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	VerifyCode *int32  `protobuf:"varint,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	Passwd     *string `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
}

func (x *RegisterRQ) Reset() {
	*x = RegisterRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRQ) ProtoMessage() {}

func (x *RegisterRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRQ.ProtoReflect.Descriptor instead.
func (*RegisterRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRQ) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *RegisterRQ) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RegisterRQ) GetVerifyCode() int32 {
	if x != nil && x.VerifyCode != nil {
		return *x.VerifyCode
	}
	return 0
}

func (x *RegisterRQ) GetPasswd() string {
	if x != nil && x.Passwd != nil {
		return *x.Passwd
	}
	return ""
}

type RegisterRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Own *int64   `protobuf:"varint,2,opt,name=own" json:"own,omitempty"`
}

func (x *RegisterRS) Reset() {
	*x = RegisterRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRS) ProtoMessage() {}

func (x *RegisterRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRS.ProtoReflect.Descriptor instead.
func (*RegisterRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *RegisterRS) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

type LoginRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own    *int64  `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Passwd *string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
}

func (x *LoginRQ) Reset() {
	*x = LoginRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRQ) ProtoMessage() {}

func (x *LoginRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRQ.ProtoReflect.Descriptor instead.
func (*LoginRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRQ) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *LoginRQ) GetPasswd() string {
	if x != nil && x.Passwd != nil {
		return *x.Passwd
	}
	return ""
}

type LoginRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err  *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Name *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (x *LoginRS) Reset() {
	*x = LoginRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRS) ProtoMessage() {}

func (x *LoginRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRS.ProtoReflect.Descriptor instead.
func (*LoginRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *LoginRS) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type SendToPersonalRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own       *int64  `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Peer      *int64  `protobuf:"varint,2,opt,name=peer" json:"peer,omitempty"`
	Content   *string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	TimeStamp *int64  `protobuf:"varint,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
}

func (x *SendToPersonalRQ) Reset() {
	*x = SendToPersonalRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToPersonalRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToPersonalRQ) ProtoMessage() {}

func (x *SendToPersonalRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToPersonalRQ.ProtoReflect.Descriptor instead.
func (*SendToPersonalRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{5}
}

func (x *SendToPersonalRQ) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *SendToPersonalRQ) GetPeer() int64 {
	if x != nil && x.Peer != nil {
		return *x.Peer
	}
	return 0
}

func (x *SendToPersonalRQ) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *SendToPersonalRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

type SendToPersonalRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (x *SendToPersonalRS) Reset() {
	*x = SendToPersonalRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToPersonalRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToPersonalRS) ProtoMessage() {}

func (x *SendToPersonalRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToPersonalRS.ProtoReflect.Descriptor instead.
func (*SendToPersonalRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{6}
}

func (x *SendToPersonalRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

type CreateTempGroupRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own       *int64  `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Name      *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Code      *int64  `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
	TimeStamp *int64  `protobuf:"varint,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
}

func (x *CreateTempGroupRQ) Reset() {
	*x = CreateTempGroupRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTempGroupRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTempGroupRQ) ProtoMessage() {}

func (x *CreateTempGroupRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTempGroupRQ.ProtoReflect.Descriptor instead.
func (*CreateTempGroupRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTempGroupRQ) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *CreateTempGroupRQ) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateTempGroupRQ) GetCode() int64 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *CreateTempGroupRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

type CreateTempGroupRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err   *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Group *int64   `protobuf:"varint,2,opt,name=group" json:"group,omitempty"`
	Code  *int64   `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
}

func (x *CreateTempGroupRS) Reset() {
	*x = CreateTempGroupRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTempGroupRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTempGroupRS) ProtoMessage() {}

func (x *CreateTempGroupRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTempGroupRS.ProtoReflect.Descriptor instead.
func (*CreateTempGroupRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTempGroupRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *CreateTempGroupRS) GetGroup() int64 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

func (x *CreateTempGroupRS) GetCode() int64 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

// 加入group就是订阅,退出就是取消
type JoinGroupRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own       *int64 `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Group     *int64 `protobuf:"varint,2,opt,name=group" json:"group,omitempty"`
	Code      *int64 `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
	TimeStamp *int64 `protobuf:"varint,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Op        *int32 `protobuf:"varint,5,opt,name=op" json:"op,omitempty"` // 0-订阅 1-取消
}

func (x *JoinGroupRQ) Reset() {
	*x = JoinGroupRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGroupRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRQ) ProtoMessage() {}

func (x *JoinGroupRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRQ.ProtoReflect.Descriptor instead.
func (*JoinGroupRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{9}
}

func (x *JoinGroupRQ) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *JoinGroupRQ) GetGroup() int64 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

func (x *JoinGroupRQ) GetCode() int64 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *JoinGroupRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

func (x *JoinGroupRQ) GetOp() int32 {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return 0
}

type JoinGroupRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err       *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	GroupName *string  `protobuf:"bytes,2,opt,name=groupName" json:"groupName,omitempty"`
}

func (x *JoinGroupRS) Reset() {
	*x = JoinGroupRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGroupRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRS) ProtoMessage() {}

func (x *JoinGroupRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRS.ProtoReflect.Descriptor instead.
func (*JoinGroupRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{10}
}

func (x *JoinGroupRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *JoinGroupRS) GetGroupName() string {
	if x != nil && x.GroupName != nil {
		return *x.GroupName
	}
	return ""
}

type SendToTempGroupRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own       *int64  `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Group     *int64  `protobuf:"varint,2,opt,name=group" json:"group,omitempty"`
	Content   *string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	TimeStamp *int64  `protobuf:"varint,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
}

func (x *SendToTempGroupRQ) Reset() {
	*x = SendToTempGroupRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToTempGroupRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToTempGroupRQ) ProtoMessage() {}

func (x *SendToTempGroupRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToTempGroupRQ.ProtoReflect.Descriptor instead.
func (*SendToTempGroupRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{11}
}

func (x *SendToTempGroupRQ) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *SendToTempGroupRQ) GetGroup() int64 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

func (x *SendToTempGroupRQ) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *SendToTempGroupRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

type SendToTempGroupRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (x *SendToTempGroupRS) Reset() {
	*x = SendToTempGroupRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToTempGroupRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToTempGroupRS) ProtoMessage() {}

func (x *SendToTempGroupRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToTempGroupRS.ProtoReflect.Descriptor instead.
func (*SendToTempGroupRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{12}
}

func (x *SendToTempGroupRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

type SubscribePersonRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own       *int64  `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Peers     []int64 `protobuf:"varint,2,rep,name=peers" json:"peers,omitempty"`
	TimeStamp *int64  `protobuf:"varint,3,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Op        *int32  `protobuf:"varint,4,opt,name=op" json:"op,omitempty"` // 0-订阅 1-取消
}

func (x *SubscribePersonRQ) Reset() {
	*x = SubscribePersonRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribePersonRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePersonRQ) ProtoMessage() {}

func (x *SubscribePersonRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePersonRQ.ProtoReflect.Descriptor instead.
func (*SubscribePersonRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribePersonRQ) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *SubscribePersonRQ) GetPeers() []int64 {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *SubscribePersonRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

func (x *SubscribePersonRQ) GetOp() int32 {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return 0
}

type SubscribePersonRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err   *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Peers []int64  `protobuf:"varint,2,rep,name=peers" json:"peers,omitempty"`
}

func (x *SubscribePersonRS) Reset() {
	*x = SubscribePersonRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribePersonRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePersonRS) ProtoMessage() {}

func (x *SubscribePersonRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePersonRS.ProtoReflect.Descriptor instead.
func (*SubscribePersonRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribePersonRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *SubscribePersonRS) GetPeers() []int64 {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SubscribeTempGroupRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own       *int64  `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Groups    []int64 `protobuf:"varint,2,rep,name=groups" json:"groups,omitempty"`
	TimeStamp *int64  `protobuf:"varint,3,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Op        *int32  `protobuf:"varint,4,opt,name=op" json:"op,omitempty"` // 0-订阅 1-取消
}

func (x *SubscribeTempGroupRQ) Reset() {
	*x = SubscribeTempGroupRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeTempGroupRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTempGroupRQ) ProtoMessage() {}

func (x *SubscribeTempGroupRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTempGroupRQ.ProtoReflect.Descriptor instead.
func (*SubscribeTempGroupRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{15}
}

func (x *SubscribeTempGroupRQ) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *SubscribeTempGroupRQ) GetGroups() []int64 {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *SubscribeTempGroupRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

func (x *SubscribeTempGroupRQ) GetOp() int32 {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return 0
}

type SubscribeTempGroupRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err    *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Groups []int64  `protobuf:"varint,2,rep,name=groups" json:"groups,omitempty"`
}

func (x *SubscribeTempGroupRS) Reset() {
	*x = SubscribeTempGroupRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeTempGroupRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTempGroupRS) ProtoMessage() {}

func (x *SubscribeTempGroupRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTempGroupRS.ProtoReflect.Descriptor instead.
func (*SubscribeTempGroupRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribeTempGroupRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *SubscribeTempGroupRS) GetGroups() []int64 {
	if x != nil {
		return x.Groups
	}
	return nil
}

type PublishPersonalMsgRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer      *int64  `protobuf:"varint,1,opt,name=peer" json:"peer,omitempty"`
	Name      *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Content   *string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	TimeStamp *int64  `protobuf:"varint,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
}

func (x *PublishPersonalMsgRQ) Reset() {
	*x = PublishPersonalMsgRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishPersonalMsgRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPersonalMsgRQ) ProtoMessage() {}

func (x *PublishPersonalMsgRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPersonalMsgRQ.ProtoReflect.Descriptor instead.
func (*PublishPersonalMsgRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{17}
}

func (x *PublishPersonalMsgRQ) GetPeer() int64 {
	if x != nil && x.Peer != nil {
		return *x.Peer
	}
	return 0
}

func (x *PublishPersonalMsgRQ) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PublishPersonalMsgRQ) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *PublishPersonalMsgRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

type PublishPersonalMsgRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishPersonalMsgRS) Reset() {
	*x = PublishPersonalMsgRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishPersonalMsgRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPersonalMsgRS) ProtoMessage() {}

func (x *PublishPersonalMsgRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPersonalMsgRS.ProtoReflect.Descriptor instead.
func (*PublishPersonalMsgRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{18}
}

type PublishGroupMsgRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group     *int64  `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Name      *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Content   *string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	TimeStamp *int64  `protobuf:"varint,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Peer      *int64  `protobuf:"varint,5,opt,name=peer" json:"peer,omitempty"`
	PeerName  *string `protobuf:"bytes,6,opt,name=peerName" json:"peerName,omitempty"`
}

func (x *PublishGroupMsgRQ) Reset() {
	*x = PublishGroupMsgRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishGroupMsgRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGroupMsgRQ) ProtoMessage() {}

func (x *PublishGroupMsgRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGroupMsgRQ.ProtoReflect.Descriptor instead.
func (*PublishGroupMsgRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{19}
}

func (x *PublishGroupMsgRQ) GetGroup() int64 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

func (x *PublishGroupMsgRQ) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PublishGroupMsgRQ) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *PublishGroupMsgRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

func (x *PublishGroupMsgRQ) GetPeer() int64 {
	if x != nil && x.Peer != nil {
		return *x.Peer
	}
	return 0
}

func (x *PublishGroupMsgRQ) GetPeerName() string {
	if x != nil && x.PeerName != nil {
		return *x.PeerName
	}
	return ""
}

type PublishGroupMsgRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishGroupMsgRS) Reset() {
	*x = PublishGroupMsgRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishGroupMsgRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGroupMsgRS) ProtoMessage() {}

func (x *PublishGroupMsgRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGroupMsgRS.ProtoReflect.Descriptor instead.
func (*PublishGroupMsgRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{20}
}

type CancelSubscribeAllRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own       *int64 `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	TimeStamp *int64 `protobuf:"varint,2,opt,name=timeStamp" json:"timeStamp,omitempty"`
}

func (x *CancelSubscribeAllRQ) Reset() {
	*x = CancelSubscribeAllRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSubscribeAllRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscribeAllRQ) ProtoMessage() {}

func (x *CancelSubscribeAllRQ) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscribeAllRQ.ProtoReflect.Descriptor instead.
func (*CancelSubscribeAllRQ) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{21}
}

func (x *CancelSubscribeAllRQ) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *CancelSubscribeAllRQ) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

type CancelSubscribeAllRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *ErrInfo `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (x *CancelSubscribeAllRS) Reset() {
	*x = CancelSubscribeAllRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSubscribeAllRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscribeAllRS) ProtoMessage() {}

func (x *CancelSubscribeAllRS) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscribeAllRS.ProtoReflect.Descriptor instead.
func (*CancelSubscribeAllRS) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{22}
}

func (x *CancelSubscribeAllRS) GetErr() *ErrInfo {
	if x != nil {
		return x.Err
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own          *int64  `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Email        *string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Name         *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Passwd       *string `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
	RegisterTime *int64  `protobuf:"varint,5,opt,name=registerTime" json:"registerTime,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{23}
}

func (x *UserInfo) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *UserInfo) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserInfo) GetPasswd() string {
	if x != nil && x.Passwd != nil {
		return *x.Passwd
	}
	return ""
}

func (x *UserInfo) GetRegisterTime() int64 {
	if x != nil && x.RegisterTime != nil {
		return *x.RegisterTime
	}
	return 0
}

type FriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Own   *int64  `protobuf:"varint,1,opt,name=own" json:"own,omitempty"`
	Peers []int64 `protobuf:"varint,2,rep,name=peers" json:"peers,omitempty"`
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_protoc_all_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_protoc_all_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_pb_protoc_all_proto_rawDescGZIP(), []int{24}
}

func (x *FriendInfo) GetOwn() int64 {
	if x != nil && x.Own != nil {
		return *x.Own
	}
	return 0
}

func (x *FriendInfo) GetPeers() []int64 {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_pb_protoc_all_proto protoreflect.FileDescriptor

var file_pb_protoc_all_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x61, 0x6c, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x57, 0x61, 0x6c, 0x22, 0x2f, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x6e, 0x0a, 0x0a, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x51, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x22, 0x3e, 0x0a, 0x0a, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x53, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x61, 0x6c, 0x2e, 0x45, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x22, 0x33, 0x0a, 0x07, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x51, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64,
	0x22, 0x3d, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x53, 0x12, 0x1e, 0x0a, 0x03, 0x65,
	0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x61, 0x6c, 0x2e, 0x45,
	0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x70, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x52, 0x51, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x32, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x6c, 0x52, 0x53, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x61, 0x6c, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x6b, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x65, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x51, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x5d, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6d, 0x70,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x53, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x61, 0x6c, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x77, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x51,
	0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f,
	0x77, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x4b, 0x0a, 0x0b, 0x4a, 0x6f,
	0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x53, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x61, 0x6c, 0x2e, 0x45, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x73, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x6f, 0x54, 0x65, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x51, 0x12, 0x10, 0x0a, 0x03,
	0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x33, 0x0a, 0x11,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x54, 0x65, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x53, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x57, 0x61, 0x6c, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x22, 0x69, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x52, 0x51, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x49, 0x0a, 0x11,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52,
	0x53, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x57, 0x61, 0x6c, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x22, 0x6e, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x51, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x77,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x4e, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x53, 0x12,
	0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57,
	0x61, 0x6c, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x76, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x52, 0x51, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x65, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x16, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x6c, 0x4d, 0x73, 0x67, 0x52, 0x53, 0x22, 0xa5, 0x01, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x51, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x65, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x13, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x73, 0x67, 0x52, 0x53, 0x22, 0x46, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x51, 0x12, 0x10, 0x0a, 0x03,
	0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x36, 0x0a, 0x14,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41,
	0x6c, 0x6c, 0x52, 0x53, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x61, 0x6c, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x6f, 0x77, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x42,
	0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x6c, 0x6c, 0x70, 0x62,
}

var (
	file_pb_protoc_all_proto_rawDescOnce sync.Once
	file_pb_protoc_all_proto_rawDescData = file_pb_protoc_all_proto_rawDesc
)

func file_pb_protoc_all_proto_rawDescGZIP() []byte {
	file_pb_protoc_all_proto_rawDescOnce.Do(func() {
		file_pb_protoc_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_protoc_all_proto_rawDescData)
	})
	return file_pb_protoc_all_proto_rawDescData
}

var file_pb_protoc_all_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pb_protoc_all_proto_goTypes = []interface{}{
	(*ErrInfo)(nil),              // 0: Wal.ErrInfo
	(*RegisterRQ)(nil),           // 1: Wal.RegisterRQ
	(*RegisterRS)(nil),           // 2: Wal.RegisterRS
	(*LoginRQ)(nil),              // 3: Wal.LoginRQ
	(*LoginRS)(nil),              // 4: Wal.LoginRS
	(*SendToPersonalRQ)(nil),     // 5: Wal.SendToPersonalRQ
	(*SendToPersonalRS)(nil),     // 6: Wal.SendToPersonalRS
	(*CreateTempGroupRQ)(nil),    // 7: Wal.CreateTempGroupRQ
	(*CreateTempGroupRS)(nil),    // 8: Wal.CreateTempGroupRS
	(*JoinGroupRQ)(nil),          // 9: Wal.JoinGroupRQ
	(*JoinGroupRS)(nil),          // 10: Wal.JoinGroupRS
	(*SendToTempGroupRQ)(nil),    // 11: Wal.SendToTempGroupRQ
	(*SendToTempGroupRS)(nil),    // 12: Wal.SendToTempGroupRS
	(*SubscribePersonRQ)(nil),    // 13: Wal.SubscribePersonRQ
	(*SubscribePersonRS)(nil),    // 14: Wal.SubscribePersonRS
	(*SubscribeTempGroupRQ)(nil), // 15: Wal.SubscribeTempGroupRQ
	(*SubscribeTempGroupRS)(nil), // 16: Wal.SubscribeTempGroupRS
	(*PublishPersonalMsgRQ)(nil), // 17: Wal.PublishPersonalMsgRQ
	(*PublishPersonalMsgRS)(nil), // 18: Wal.PublishPersonalMsgRS
	(*PublishGroupMsgRQ)(nil),    // 19: Wal.PublishGroupMsgRQ
	(*PublishGroupMsgRS)(nil),    // 20: Wal.PublishGroupMsgRS
	(*CancelSubscribeAllRQ)(nil), // 21: Wal.CancelSubscribeAllRQ
	(*CancelSubscribeAllRS)(nil), // 22: Wal.CancelSubscribeAllRS
	(*UserInfo)(nil),             // 23: Wal.UserInfo
	(*FriendInfo)(nil),           // 24: Wal.FriendInfo
}
var file_pb_protoc_all_proto_depIdxs = []int32{
	0, // 0: Wal.RegisterRS.err:type_name -> Wal.ErrInfo
	0, // 1: Wal.LoginRS.err:type_name -> Wal.ErrInfo
	0, // 2: Wal.SendToPersonalRS.err:type_name -> Wal.ErrInfo
	0, // 3: Wal.CreateTempGroupRS.err:type_name -> Wal.ErrInfo
	0, // 4: Wal.JoinGroupRS.err:type_name -> Wal.ErrInfo
	0, // 5: Wal.SendToTempGroupRS.err:type_name -> Wal.ErrInfo
	0, // 6: Wal.SubscribePersonRS.err:type_name -> Wal.ErrInfo
	0, // 7: Wal.SubscribeTempGroupRS.err:type_name -> Wal.ErrInfo
	0, // 8: Wal.CancelSubscribeAllRS.err:type_name -> Wal.ErrInfo
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pb_protoc_all_proto_init() }
func file_pb_protoc_all_proto_init() {
	if File_pb_protoc_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_protoc_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToPersonalRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToPersonalRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTempGroupRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTempGroupRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGroupRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGroupRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToTempGroupRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToTempGroupRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribePersonRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribePersonRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeTempGroupRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeTempGroupRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishPersonalMsgRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishPersonalMsgRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishGroupMsgRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishGroupMsgRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelSubscribeAllRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelSubscribeAllRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_protoc_all_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_protoc_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_protoc_all_proto_goTypes,
		DependencyIndexes: file_pb_protoc_all_proto_depIdxs,
		MessageInfos:      file_pb_protoc_all_proto_msgTypes,
	}.Build()
	File_pb_protoc_all_proto = out.File
	file_pb_protoc_all_proto_rawDesc = nil
	file_pb_protoc_all_proto_goTypes = nil
	file_pb_protoc_all_proto_depIdxs = nil
}
